Repository johnsonjh/duma, pull requests merged in 2020-12, with the labels that each got.

#18 README: Add DeepScan badge
  README.md
Labels: automation, bot, enhancement

#20 README: Remove tag badge
  README.md
Labels: formatting, low-priority

#21 README: Remove tag links
  README.md
Labels: documentation, formatting, low-priority

#22 Add a Codacy badge to README.md
  README.md
Labels: automation, bot, documentation
