Repository johnsonjh/duma, pull requests merged in 2021-06, with the labels that each got.

#102 Update SECURITY.md
  SECURITY.md
Labels: documentation

#99 generate duma.sh, to have absolute path to installed shared library
  CMakeLists.txt
  INSTALL
  duma.sh.in
Labels: enhancement

#104 Update README.md
  README.md
Labels: documentation, merge when passing
